# Generated by Django 5.2.7 on 2025-10-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_rename_catrgory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
