# Generated by Django 5.2.7 on 2025-10-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='source_id',
            field=models.CharField(blank=True, help_text='Original spreadsheet id / ISBN or source identifier', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
